name: python pipelne

on: [push, workflow_dispatch]

env:
  SERVICE_NAME: python-script-service



jobs:
  lint-and-test:
    name: Lint and test the Python code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5

      - name: Install Requirement
        run: pip install flake8 pylint

      - name: Lint hello.py
        run: |
          flake8 hello.py
          pylint hello.py

      - name: Run Unit Tests
        run: python hello.py | grep -i hello || exit 1

  build-and-push:
    name: Build and push container image to ghcr
    needs: [lint-and-test]
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=,suffix=
            type=sha,format=long,prefix=,suffix=
            type=ref,event=branch,prefix=,suffix=

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platform: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  test-image:
    name: Test Image
    needs: [ build-and-push ]
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the Python Script container image from GHCR 
        run: docker pull ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Run Python Script image ${{ env.SERVICE_NAME }}
        run: |
          docker run \
            --rm --detach --publish 8080:8080 \
            --name $SERVICE_NAME ghcr.io/${{ github.repository }}:${{ github.sha }}
          sleep 3 #allow time for service to start

      # - name: Run tests using the container image
      #   run:
      #     docker exec $SERVICE_NAME

      - name: Stop ${{ env.SERVICE_NAME }}
        run: docker stop $SERVICE_NAME


